sudo: required

language: python

python:
  - "3.6"

services:
  - docker

branches:
  only:
    - master
    - develop

install:
  - pip install codecov
  - docker-compose build

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    secure: >
      YWsjVzpT9e9taR1EyfqkAeLjDxXYdCZzv94BJFzf2UjoBztqINOZI/8bVj7kpJuSg0evQHNfyq
      BDtw/yM9dHaoMyVcl2qw9yteO9IGc0SltNMII6hFSDchpty9OS/WXvItzI7MRSsJCEEAGnzns3
      84/PXggtP998nPxTLk8btGVMcp44rUj1YD119/TumOYhrn/qrnchmKFYwVChfEYBMY7bB46bYn
      I7MyS3ldWzKc1kOYDQCxxo6Ncja5+v+jDSVR8jO+Mgi+9ploENKtORkgLeGSKNXHNDzRLPo+Xv
      Sudi4co8qyQqP/FrxViml7vEN7OoGRtR7nR/UQ1pO4LHlHu+G9r1Y8D0aZINCjZklAF+kX/EOZ
      iCkRuuO9C8w45p3ICtEXFrMS8IyBXmuU1MDx/NHJsau3ROqlZ4suM+Tz79REYrRX10DpERM8PR
      cv33++7D1POtwlUwPY+lM1nkrY//W8Xf5iZM3VxLO0e1HqiW6oTyxkrNeO7X03QrlXPEdSbbv5
      zvRLQ+NV+Nwa4hyosAmBgjv9iShOHHNgtYAvRxlexHHdjdE/1r9sDg7t10koTC/mt2iw5TkHzQ
      DI3Cfmq4l9dX2TD6aE7i2C7UxLpq+iCC49y48k8B7tQWPhmyBLA0qx0mlDfTItEEbrMLCTyLCK
      yl60uUuU7iDf2IvUM=
