language: python

sudo: required
dist: trusty

services:
  - postgresql

matrix:
  fast_finish: true
  include:
    - python: "3.5"
  allow_failures:
    - os: osx

# `travis lint` is marking this section as a false positive!
# References:
#  - https://github.com/travis-ci/travis-ci/issues/3663
#  - https://github.com/travis-ci/travis-ci/issues/5396
addons:
  apt:
    packages:
      - libffi-dev
      - python3-dev
  postgresql: "9.5"

branches:
  only:
    - master
    - release

before_install:
  - echo Travis OS Name ... ${TRAVIS_OS_NAME}
  - echo Travis Python .... ${TRAVIS_PYTHON_VERSION}
  - echo Python Version ... $(python --version)

install:
  - pip install --upgrade pip
  - pip install --upgrade --requirement requirements-travis.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    secure: >
      YWsjVzpT9e9taR1EyfqkAeLjDxXYdCZzv94BJFzf2UjoBztqINOZI/8bVj7kpJuSg0evQHNfyq
      BDtw/yM9dHaoMyVcl2qw9yteO9IGc0SltNMII6hFSDchpty9OS/WXvItzI7MRSsJCEEAGnzns3
      84/PXggtP998nPxTLk8btGVMcp44rUj1YD119/TumOYhrn/qrnchmKFYwVChfEYBMY7bB46bYn
      I7MyS3ldWzKc1kOYDQCxxo6Ncja5+v+jDSVR8jO+Mgi+9ploENKtORkgLeGSKNXHNDzRLPo+Xv
      Sudi4co8qyQqP/FrxViml7vEN7OoGRtR7nR/UQ1pO4LHlHu+G9r1Y8D0aZINCjZklAF+kX/EOZ
      iCkRuuO9C8w45p3ICtEXFrMS8IyBXmuU1MDx/NHJsau3ROqlZ4suM+Tz79REYrRX10DpERM8PR
      cv33++7D1POtwlUwPY+lM1nkrY//W8Xf5iZM3VxLO0e1HqiW6oTyxkrNeO7X03QrlXPEdSbbv5
      zvRLQ+NV+Nwa4hyosAmBgjv9iShOHHNgtYAvRxlexHHdjdE/1r9sDg7t10koTC/mt2iw5TkHzQ
      DI3Cfmq4l9dX2TD6aE7i2C7UxLpq+iCC49y48k8B7tQWPhmyBLA0qx0mlDfTItEEbrMLCTyLCK
      yl60uUuU7iDf2IvUM=
