version: '2'

services:
  bot:
    build:
      context: ./bot/
    environment:
      - MRB_ADMIN_ID=${MRB_ADMIN_ID}
      - MRB_DISCORD_TOKEN=${MRB_DISCORD_TOKEN}

  web:
    build:
      context: ./web/
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
