version: '2'

services:
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
      args:
        MRB_ENV: ${MRB_ENV}
    environment:
      MRB_DISCORD_TOKEN: ${MRB_DISCORD_TOKEN}
      MRB_ENV: ${MRB_ENV}

volumes:
  mrb_data: {}
  mrb_test_data: {}
