#!/usr/bin/env bash

MRB_PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
pushd ${MRB_PROJECT_DIR} > /dev/null

docker-compose stop web web_dev
docker-compose start postgres

docker-compose run --rm postgres psql -h postgres -U postgres -c \
    "drop database if exists mrb;"

docker-compose run --rm postgres psql -h postgres -U postgres -c \
    "create database mrb owner mrb;"

echo "Downloading database from Heroku ..."
curl --progress-bar "$(heroku pg:backups public-url)" -o db.dump
echo "Database downloaded"

docker-compose run --rm postgres pg_restore --verbose --no-acl --no-owner \
    -h postgres -U postgres -d mrb /opt/db.dump

rm db.dump

docker-compose start web_dev
docker-compose exec web_dev python3 manage.py migrate --noinput
docker-compose start web

popd > /dev/null
