# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_discord', '0002_add_username_discriminator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='The username for this user', max_length=32),
        ),
    ]
